### ISSUE TITLE
how to use not in reducer

### ISSUE THREAD

**Issue by MajorMayer** [sergiodxa/use-safe-callback#3]

**Comment by sergiodxa** [comment]
You should be able to use it with useState too.

```js
const [state, unsafeSetState] = React.useState(initialState);
const safeSetState = useSafeCallback(unsafeSetState);
// somewhere else, like an effect or event handler
safeSetState(newValue)
```

This Hook is not useful for other callbacks aside of setState or dispatch, but you could totally do it in case you want to avoid calling a custom function (like an even handler) if the component unmounted.

```js
const unsafeHandleClick = React.useCallback(event => {
  // do something here, maybe a Fetch call and a state update combined
}, [setState, props.someProp]);

const safeHandleClick = useSafeCallback(unsafeHandleClick);

return <button onClick={safeHandleClick}>Label</button>
```

This way, the `unsafeHandleClick` function will not be called if the component is unmounted, however, this shouldn't happen anyway.
